src/error.h File Reference
header file for error
#include <stdio.h>
*
#include <stdlib.h>
*
#include <string.h>
*
#include <errno.h>
*
#include <assert.h>
*
Functions
void sys_err (const char *)
if an error occured then print the error message and exit from program
Detailed Description
header file for error
Author
M. Ozgan, mozgan@mozgan.org
Version
0.1
Date
23.08.2013 22:20:44
Compiler
gcc (on Mac, and 4.4BSD)
Company
TU Wien
Bug
Bug none
Todo
Todo none
Definition in file error.h.
Function Documentation
void sys_err (const char * msg)
if an error occured then print the error message and exit from program
Parameters
msg programmer message to print
Definition at line 35 of file error.c.
Referenced by binding(), close_socket(), communication(), and make_socket().