src/udp.h File Reference
header file for udp communication
#include <stdio.h>
*
#include <stdlib.h>
*
#include <string.h>
*
#include <unistd.h>
*
#include <netdb.h>
*
#include <sys/types.h>
*
#include <netinet/in.h>
*
#include <arpa/inet.h>
*
#include <sys/socket.h>
*
Macros
#define u_long unsigned long
#define h_addr h_addr_list[0]
Functions
void make_socket (const char *, unsigned int)
make the socket
void binding (void)
bind to host
void communication (void)
make the communication with host (recv or send the datagrams)
void close_socket (void)
close the socket if not to use in future
Variables
struct hostent * h_name
struct sockaddr_in dest_addr
struct sockaddr_in serv_addr
int sock_fd
unsigned int port_nr
Detailed Description
header file for udp communication
Author
M. Ozgan, mozgan@mozgan.org
Version
0.1
Date
23.08.2013 22:02:31
Compiler
gcc (on Mac, and 4.4BSD)
Company
TU Wien
Bug
Bug none
Todo
Todo none
Definition in file udp.h.
Macro Definition Documentation
#define h_addr h_addr_list[0]
Definition at line 52 of file udp.h.
#define u_long unsigned long
Definition at line 45 of file udp.h.
Referenced by make_socket().
Function Documentation
void binding (void)
bind to host
bind to the socket
Definition at line 60 of file udp.c.
References serv_addr, sock_fd, and sys_err().
Referenced by main().
void close_socket (void)
close the socket if not to use in future
close the open socket
Definition at line 108 of file udp.c.
References sock_fd, and sys_err().
Referenced by main().
void communication (void)
make the communication with host (recv or send the datagrams)
communication
Definition at line 70 of file udp.c.
References dest_addr, sock_fd, and sys_err().
Referenced by main().
void make_socket (const char * hostname, unsigned int port)
make the socket
make a socket
Parameters
hostname get the hostname
port port number to connection
Definition at line 37 of file udp.c.
References dest_addr, h_name, serv_addr, sock_fd, sys_err(), and u_long.
Referenced by main().
Variable Documentation
struct sockaddr_in dest_addr
destination address
Definition at line 57 of file udp.h.
Referenced by communication(), and make_socket().
struct hostent* h_name
real hostname
Definition at line 55 of file udp.h.
Referenced by make_socket().
unsigned int port_nr
port number
Definition at line 61 of file udp.h.
Referenced by main().
struct sockaddr_in serv_addr
server address
Definition at line 58 of file udp.h.
Referenced by binding(), and make_socket().
int sock_fd
socket description
Definition at line 60 of file udp.h.
Referenced by binding(), close_socket(), communication(), and make_socket().