src/udp.c File Reference
udp communication
#include `udp.h`
*
#include `error.h`
*
Functions
void make_socket (const char *hostname, unsigned int port)
make the socket
void binding (void)
bind to host
void communication (void)
make the communication with host (recv or send the datagrams)
void close_socket (void)
close the socket if not to use in future
Detailed Description
udp communication
Author
M. Ozgan, mozgan@mozgan.org
Version
0.1
Date
23.08.2013 22:01:48
Compiler
gcc (on Mac, and 4.4BSD)
Company
TU Wien
Bug
Bug none
Todo
Todo none
Definition in file udp.c.
Function Documentation
void binding (void)
bind to host
bind to the socket
Definition at line 60 of file udp.c.
References serv_addr, sock_fd, and sys_err().
Referenced by main().
void close_socket (void)
close the socket if not to use in future
close the open socket
Definition at line 108 of file udp.c.
References sock_fd, and sys_err().
Referenced by main().
void communication (void)
make the communication with host (recv or send the datagrams)
communication
Definition at line 70 of file udp.c.
References dest_addr, sock_fd, and sys_err().
Referenced by main().
void make_socket (const char * hostname, unsigned int port)
make the socket
Parameters
hostname get the hostname
port port number to connection
Definition at line 37 of file udp.c.
References dest_addr, h_name, serv_addr, sock_fd, sys_err(), and u_long.
Referenced by main().