lib/buffer.c File Reference
library for ring-buffer
#include <lib/buffer.h>
*
Functions
void buffer_init (void)
initialize the ring buffer
void buffer_write (uint16_t c)
write the new data in ring buffer
float buffer_medium (void)
calculate the medium of ring buffer
Detailed Description
library for ring-buffer
Author
M. Ozgan, mozgan@mozgan.org
Version
0.5
Date
20.08.2013 20:28:03
Compiler
gcc (on Mac, and 4.4BSD)
Company
TU Wien
Bug
Bug none
Todo
Todo none
Definition in file buffer.c.
Function Documentation
void buffer_init (void)
initialize the ring buffer
Definition at line 33 of file buffer.c.
References head, and tail.
Referenced by main().
float buffer_medium (void)
calculate the medium of ring buffer
Returns
Definition at line 59 of file buffer.c.
References buffer, and LEN.
Referenced by main().
void buffer_write (uint16_t c)
write the new data in ring buffer
Parameters
c new data to write in ring buffer
Definition at line 45 of file buffer.c.
References buffer, head, and LEN.
Referenced by trigger().