driver/enc28j60.c File Reference
ENC28J60 ethernet driver.
#include <board/freq.h>
*
#include <device/enc28j60.h>
*
#include <driver/spi.h>
*
Functions
void enc_start (void)
start ENC28J60 pin to write or to read
void enc_stop (void)
stop the ENC28J60 pin
void enc_set_mac (uint8_t mymac[])
set the mac-address to BANK3 register
void enc_init (uint8_t mymac[])
initialize the ENC28J60
void enc_write_op (uint8_t op, uint8_t addr, uint8_t data)
write the operation
void enc_write (uint8_t addr, uint8_t data)
write on ENC28J60
void enc_set_bank (uint8_t addr)
set the bank on address
void enc_write_phy (uint8_t addr, uint16_t data)
write the data on ENC28J60 physical address
uint16_t enc_read_phy (uint8_t addr)
read from physical address of ENC28J60
uint8_t enc_read (uint8_t addr)
read from from address of ENC28J60
uint8_t enc_read_op (uint8_t op, uint8_t addr)
read the operation from address of ENC28J60
void enc_init_phy (void)
initialize the physical interface of ENC28J60
void enc_read_buf (uint16_t len, uint8_t *data)
read from the buffer
void enc_write_buf (uint16_t len, uint8_t *data)
write the buffer
uint8_t enc_get_rev (void)
get the revision of ENC28J60
void enc_send_packet (uint16_t len, uint8_t *packet)
send a packet to ethernet
uint16_t enc_recv_packet (uint16_t maxlen, uint8_t *packet)
receive a packet from ethernet
Variables
uint8_t enc_bank
unsigned int p_next
Detailed Description
ENC28J60 ethernet driver.
Author
M. Ozgan, mozgan@mozgan.org
Version
1.0
Date
19.08.2013 18:51:18
Compiler
gcc (on Mac, and 4.4BSD)
Company
TU Wien
Bug
Bug 'enc_send_packet' gives a warning with compiler option '-Woverflow'. You can devide as bytes the 16-bit registers.
Todo
Todo none
Definition in file enc28j60.c.
Function Documentation
uint8_t enc_get_rev (void)
get the revision of ENC28J60
Returns
revision
Definition at line 332 of file enc28j60.c.
References enc_read(), and EREVID.
void enc_init (uint8_t mymac[])
initialize the ENC28J60
Parameters
mymac[] my mac address
Definition at line 74 of file enc28j60.c.
References BIT_FIELD_SET, CLKRDY, CRCEN, E_RXEN, ECON1, EIE, ENC_CTRL_CS, ENC_CTRL_DDR, ENC_CTRL_PORT, enc_read(), enc_set_bank(), enc_set_mac(), enc_write(), enc_write_op(), enc_write_phy(), EPMCSH, EPMCSL, EPMM0, EPMM1, ERXFCON, ERXNDH, ERXNDL, ERXRDPTH, ERXRDPTL, ERXSTH, ERXSTL, ESTAT, ETXNDH, ETXNDL, ETXSTH, ETXSTL, FRMLNEN, HDLDIS, INTIE, MABBIPG, MACON1, MACON2, MACON3, MAIPGH, MAIPGL, MAMXFLH, MAMXFLL, MARXEN, MAX_FRAME_LEN, p_next, PADCFG0, PHCON2, PKTIE, PMEN, RX_START_INIT, RX_STOP_INIT, RXPAUS, SOFT_RESET, spi_init(), TX_START_INIT, TX_STOP_INIT, TXCRCEN, TXPAUS, and UCEN.
void enc_init_phy (void)
initialize the physical interface of ENC28J60
Definition at line 270 of file enc28j60.c.
References enc_write_phy(), and PHLCON.
Referenced by main().
uint8_t enc_read (uint8_t addr)
read from from address of ENC28J60
Parameters
addr address
Returns
operation
Definition at line 235 of file enc28j60.c.
References enc_read_op(), enc_set_bank(), and READ_CTRL_REG.
Referenced by enc_get_rev(), enc_init(), enc_read_phy(), enc_recv_packet(), and enc_write_phy().
void enc_read_buf (uint16_t len, uint8_t * data)
read from the buffer
Parameters
len length of data
data data to read
Definition at line 295 of file enc28j60.c.
References enc_start(), enc_stop(), READ_BUF_MEM, spi_read(), and spi_write().
Referenced by enc_recv_packet().
uint8_t enc_read_op (uint8_t op, uint8_t addr)
read the operation from address of ENC28J60
Parameters
op operation
addr address
Returns
data from SPI
Definition at line 251 of file enc28j60.c.
References enc_start(), enc_stop(), spi_read_addr(), spi_write(), and spi_write_op().
Referenced by enc_read(), and enc_recv_packet().
uint16_t enc_read_phy (uint8_t addr)
read from physical address of ENC28J60
Parameters
addr address
Returns
data
Definition at line 209 of file enc28j60.c.
References BUSY, enc_read(), enc_write(), MICMD, MIIRD, MIRDH, MIRDL, MIREGADR, and MISTAT.
uint16_t enc_recv_packet (uint16_t maxlen, uint8_t * packet)
receive a packet from ethernet
Parameters
maxlen maximum length of packet to receive
packet packet to receive
Returns
length of received packet
Definition at line 368 of file enc28j60.c.
References BIT_FIELD_SET, ECON2, enc_read(), enc_read_buf(), enc_read_op(), enc_write(), enc_write_op(), EPKTCNT, ERDPTH, ERDPTL, ERXRDPTH, ERXRDPTL, MIN, p_next, PKTDEC, and READ_BUF_MEM.
Referenced by main().
void enc_send_packet (uint16_t len, uint8_t * packet)
send a packet to ethernet
Parameters
len length of packet
packet packet to send
Definition at line 344 of file enc28j60.c.
References BIT_FIELD_SET, ECON1, enc_write(), enc_write_buf(), enc_write_op(), ETXNDH, ETXNDL, EWRPTH, EWRPTL, TX_START_INIT, TXRTS, and WRITE_BUF_MEM.
Referenced by arp_answer(), echo_reply(), and udp_reply().
void enc_set_bank (uint8_t addr)
set the bank on address
Parameters
addr address to set
Definition at line 174 of file enc28j60.c.
References ADDR_MASK, BANK_MASK, BIT_FIELD_CLR, BIT_FIELD_SET, BSEL0, BSEL1, ECON1, enc_bank, and enc_write_op().
Referenced by enc_init(), enc_read(), and enc_write().
void enc_set_mac (uint8_t mymac[])
set the mac-address to BANK3 register
Parameters
mymac[] my mac address
Definition at line 58 of file enc28j60.c.
References enc_write(), MAADR0, MAADR1, MAADR2, MAADR3, MAADR4, and MAADR5.
Referenced by enc_init().
void enc_start (void)
start ENC28J60 pin to write or to read
Definition at line 38 of file enc28j60.c.
References ENC_CTRL_CS, and ENC_CTRL_PORT.
Referenced by enc_read_buf(), enc_read_op(), enc_write_buf(), and enc_write_op().
void enc_stop (void)
stop the ENC28J60 pin
Definition at line 47 of file enc28j60.c.
References ENC_CTRL_CS, and ENC_CTRL_PORT.
Referenced by enc_read_buf(), enc_read_op(), enc_write_buf(), and enc_write_op().
void enc_write (uint8_t addr, uint8_t data)
write on ENC28J60
Parameters
addr address to write
data data to send
Definition at line 162 of file enc28j60.c.
References enc_set_bank(), enc_write_op(), and WRITE_CTRL_REG.
Referenced by enc_init(), enc_read_phy(), enc_recv_packet(), enc_send_packet(), enc_set_mac(), and enc_write_phy().
void enc_write_buf (uint16_t len, uint8_t * data)
write the buffer
Parameters
len length of data
data data
Definition at line 314 of file enc28j60.c.
References enc_start(), enc_stop(), spi_write(), and WRITE_BUF_MEM.
Referenced by enc_send_packet().
void enc_write_op (uint8_t op, uint8_t addr, uint8_t data)
write the operation
Parameters
op operation to write on SPI
addr address to write
data data to send on SPI
Definition at line 145 of file enc28j60.c.
References enc_start(), enc_stop(), spi_write(), and spi_write_op().
Referenced by enc_init(), enc_recv_packet(), enc_send_packet(), enc_set_bank(), and enc_write().
void enc_write_phy (uint8_t addr, uint16_t data)
write the data on ENC28J60 physical address
Parameters
addr address
data data
Definition at line 190 of file enc28j60.c.
References BUSY, enc_read(), enc_write(), MIREGADR, MISTAT, MIWRH, and MIWRL.
Referenced by enc_init(), and enc_init_phy().
Variable Documentation
uint8_t enc_bank
Definition at line 31 of file enc28j60.c.
Referenced by enc_set_bank().
unsigned int p_next
Definition at line 32 of file enc28j60.c.
Referenced by enc_init(), and enc_recv_packet().