device/enc28j60.h File Reference
registers of ENC28J60 device
#include <board/freq.h>
*
#include <include/common.h>
*
#include <inttypes.h>
*
Macros
#define ADDR_MASK 0x1F
#define BANK_MASK 0x60
#define SPRD_MASK 0x80
#define EIE 0x1B
#define INTIE 0x80
#define PKTIE 0x40
#define DMAIE 0x20
#define LINKIE 0x10
#define TXIE 0x08
#define EIE_WOLIE 0x04
#define TXERIE 0x02
#define RXERIE 0x01
#define EIR 0x1C
#define PKTIF 0x40
#define DMAIF 0x20
#define LINKIF 0x10
#define TXIF 0x08
#define EIR_WOLIF 0x04
#define TXERIF 0x02
#define RXERIF 0x01
#define ESTAT 0x1D
#define INT 0x80
#define BUFER 0x40
#define ESTAT_R 0x20
#define LATECOL 0x10
#define RXBUSY 0x04
#define TXABRT 0x02
#define CLKRDY 0x01
#define ECON2 0x1E
#define AUTOINC 0x80
#define PKTDEC 0x40
#define PWRSV 0x20
#define ECON2_R 0x10
#define VRPF 0x08
#define ECON1 0x1F
#define TXRST 0x80
#define RXRST 0x40
#define DMAST 0x20
#define CSUMEN 0x10
#define TXRTS 0x08
#define E_RXEN 0x04
#define BSEL1 0x02
#define BSEL0 0x01
#define BANK0 (0x00)
#define ERDPTL (0x00 | BANK0)
#define ERDPTH (0x01 | BANK0)
#define EWRPTL (0x02 | BANK0)
#define EWRPTH (0x03 | BANK0)
#define ETXSTL (0x04 | BANK0)
#define ETXSTH (0x05 | BANK0)
#define ETXNDL (0x06 | BANK0)
#define ETXNDH (0x07 | BANK0)
#define ERXSTL (0x08 | BANK0)
#define ERXSTH (0x09 | BANK0)
#define ERXNDL (0x0A | BANK0)
#define ERXNDH (0x0B | BANK0)
#define ERXRDPTL (0x0C | BANK0)
#define ERXRDPTH (0x0D | BANK0)
#define ERXWRPTL (0x0E | BANK0)
#define ERXWRPTH (0x0F | BANK0)
#define EDMASTL (0x10 | BANK0)
#define EDMASTH (0x11 | BANK0)
#define EDMANDL (0x12 | BANK0)
#define EDMANDH (0x13 | BANK0)
#define EDMADSTL (0x14 | BANK0)
#define EDMADSTH (0x15 | BANK0)
#define EDMACSL (0x16 | BANK0)
#define EDMACSH (0x17 | BANK0)
#define BANK1 (0x20)
#define EHT0 (0x00 | BANK1)
#define EHT1 (0x01 | BANK1)
#define EHT2 (0x02 | BANK1)
#define EHT3 (0x03 | BANK1)
#define EHT4 (0x04 | BANK1)
#define EHT5 (0x05 | BANK1)
#define EHT6 (0x06 | BANK1)
#define EHT7 (0x07 | BANK1)
#define EPMM0 (0x08 | BANK1)
#define EPMM1 (0x09 | BANK1)
#define EPMM2 (0x0A | BANK1)
#define EPMM3 (0x0B | BANK1)
#define EPMM4 (0x0C | BANK1)
#define EPMM5 (0x0D | BANK1)
#define EPMM6 (0x0E | BANK1)
#define EPMM7 (0x0F | BANK1)
#define EPMCSL (0x10 | BANK1)
#define EPMCSH (0x11 | BANK1)
#define EPMOL (0x14 | BANK1)
#define EPMOH (0x15 | BANK1)
#define EWOLIE (0x16 | BANK1)
#define EWOLIR (0x17 | BANK1)
#define ERXFCON (0x18 | BANK1)
#define EPKTCNT (0x19 | BANK1)
#define BANK2 (0x40)
#define MACON1 (0x00 | BANK2 | 0x80)
#define MACON2 (0x01 | BANK2 | 0x80)
#define MACON3 (0x02 | BANK2 | 0x80)
#define MACON4 (0x03 | BANK2 | 0x80)
#define MABBIPG (0x04 | BANK2 | 0x80)
#define MAIPGL (0x06 | BANK2 | 0x80)
#define MAIPGH (0x07 | BANK2 | 0x80)
#define MACLCON1 (0x08 | BANK2 | 0x80)
#define MACLCON2 (0x09 | BANK2 | 0x80)
#define MAMXFLL (0x0A | BANK2 | 0x80)
#define MAMXFLH (0x0B | BANK2 | 0x80)
#define MAPHSUP (0x0D | BANK2 | 0x80)
#define MICON (0x11 | BANK2 | 0x80)
#define MICMD (0x12 | BANK2 | 0x80)
#define MIREGADR (0x14 | BANK2 | 0x80)
#define MIWRL (0x16 | BANK2 | 0x80)
#define MIWRH (0x17 | BANK2 | 0x80)
#define MIRDL (0x18 | BANK2 | 0x80)
#define MIRDH (0x19 | BANK2 | 0x80)
#define BANK3 (0x60)
#define MAADR1 (0x00 | BANK3 | 0x80)
#define MAADR0 (0x01 | BANK3 | 0x80)
#define MAADR3 (0x02 | BANK3 | 0x80)
#define MAADR2 (0x03 | BANK3 | 0x80)
#define MAADR5 (0x04 | BANK3 | 0x80)
#define MAADR4 (0x05 | BANK3 | 0x80)
#define EBSTSD (0x06 | BANK3)
#define EBSTCON (0x07 | BANK3)
#define EBSTCSL (0x08 | BANK3)
#define EBSTCSH (0x09 | BANK3)
#define MISTAT (0x0A | BANK3 | 0x80)
#define EREVID (0x12 | BANK3)
#define ECOCON (0x15 | BANK3)
#define EFLOCON (0x17 | BANK3)
#define EPAUSL (0x18 | BANK3)
#define EPAUSH (0x19 | BANK3)
#define PHCON1 0x00
#define PRST 0x8000
#define PLOOPBK 0x4000
#define PPWRSV 0x0800
#define PDPXMD 0x0100
#define PHSTAT1 0x01
#define PFDPX 0x1000
#define PHDPX 0x0800
#define LLSTAT 0x0004
#define JBSTAT 0x0002
#define PHHID1 0x02
#define PHHID2 0x03
#define PHCON2 0x10
#define FRCLNK 0x4000
#define TXDIS 0x2000
#define JABBER 0x0400
#define HDLDIS 0x0100
#define PHSTAT2 0x11
#define TXSTAT 0x2000
#define RXSTAT 0x1000
#define COLSTAT 0x0800
#define LSTAT 0x0400
#define DPXSTAT 0x0200
#define PLRITY 0x0020
#define PHIE 0x12
#define PLNKIE 0x0010
#define PGEIE 0x0002
#define PHIR 0x13
#define PLNKIF 0x0010
#define PGIF 0x0004
#define PHLCON 0x14
#define LACFG3 0x0800
#define LACFG2 0x0400
#define LACFG1 0x0200
#define LACFG0 0x0100
#define LBCFG3 0x0080
#define LBCFG2 0x0040
#define LBCFG1 0x0020
#define LBCFG0 0x0010
#define LFRQ1 0x0008
#define LFRQ0 0x0004
#define STRCH 0x0002
#define UCEN 0x80
#define ANDOR 0x40
#define CRCEN 0x20
#define PMEN 0x10
#define MPEN 0x08
#define HTEN 0x04
#define MCEN 0x02
#define BCEN 0x01
#define LOOPBK 0x10
#define TXPAUS 0x08
#define RXPAUS 0x04
#define PASSALL 0x02
#define MARXEN 0x01
#define MARST 0x80
#define RNDRST 0x40
#define MARXRST 0x08
#define RFUNRST 0x04
#define MATXRST 0x02
#define TFUNRST 0x01
#define PADCFG2 0x80
#define PADCFG1 0x40
#define PADCFG0 0x20
#define TXCRCEN 0x10
#define PHDREN 0x08
#define HFRMEN 0x04
#define FRMLNEN 0x02
#define FULDPX 0x01
#define MIISCAN 0x02
#define MIIRD 0x01
#define NVALID 0x04
#define SCAN 0x02
#define BUSY 0x01
#define PHUGEEN 0x08
#define PPADEN 0x04
#define PCRCEN 0x02
#define POVERRIDE 0x01
#define READ_CTRL_REG 0x00
#define READ_BUF_MEM 0x3A
#define WRITE_CTRL_REG 0x40
#define WRITE_BUF_MEM 0x7A
#define BIT_FIELD_SET 0x80
#define BIT_FIELD_CLR 0xA0
#define SOFT_RESET 0xFF
#define RX_START_INIT 0x00
#define RX_STOP_INIT (0x1FFF - 0x0600 - 1)
#define TX_START_INIT (0x1FFF - 0x0600)
#define TX_STOP_INIT 0x1FFF
#define MAX_FRAME_LEN 1500
Functions
void enc_start (void)
start ENC28J60 pin to write or to read
void enc_stop (void)
stop the ENC28J60 pin
void enc_init (uint8_t *)
void enc_write_op (uint8_t, uint8_t, uint8_t)
write the operation
void enc_write (uint8_t, uint8_t)
write on ENC28J60
void enc_set_bank (uint8_t)
set the bank on address
void enc_write_phy (uint8_t, uint16_t)
write the data on ENC28J60 physical address
uint16_t enc_read_phy (uint8_t)
read from physical address of ENC28J60
uint8_t enc_read (uint8_t)
read from from address of ENC28J60
uint8_t enc_read_op (uint8_t, uint8_t)
read the operation from address of ENC28J60
void enc_init_phy (void)
initialize the physical interface of ENC28J60
void enc_set_mac (uint8_t *)
void enc_read_buf (uint16_t, uint8_t *)
read from the buffer
void enc_write_buf (uint16_t, uint8_t *)
write the buffer
uint8_t enc_get_rev (void)
get the revision of ENC28J60
void enc_send_packet (uint16_t, uint8_t *)
send a packet to ethernet
uint16_t enc_recv_packet (uint16_t, uint8_t *)
receive a packet from ethernet
Detailed Description
registers of ENC28J60 device
Author
M. Ozgan, mozgan@mozgan.org
Version
1.0
Date
19.08.2013 15:23:13
Compiler
gcc (on Mac, and 4.4BSD)
Company
TU Wien
Bug
Bug none
Todo
Todo none
Definition in file enc28j60.h.
Macro Definition Documentation
#define ADDR_MASK 0x1F
Definition at line 46 of file enc28j60.h.
Referenced by enc_set_bank(), and spi_write_op().
#define ANDOR 0x40
Definition at line 378 of file enc28j60.h.
#define AUTOINC 0x80
Definition at line 111 of file enc28j60.h.
#define BANK0 (0x00)
Definition at line 138 of file enc28j60.h.
#define BANK1 (0x20)
Definition at line 168 of file enc28j60.h.
#define BANK2 (0x40)
Definition at line 198 of file enc28j60.h.
#define BANK3 (0x60)
Definition at line 222 of file enc28j60.h.
#define BANK_MASK 0x60
Definition at line 47 of file enc28j60.h.
Referenced by enc_set_bank().
#define BCEN 0x01
Definition at line 384 of file enc28j60.h.
#define BIT_FIELD_CLR 0xA0
Definition at line 475 of file enc28j60.h.
Referenced by enc_set_bank().
#define BIT_FIELD_SET 0x80
Definition at line 474 of file enc28j60.h.
Referenced by enc_init(), enc_recv_packet(), enc_send_packet(), and enc_set_bank().
#define BSEL0 0x01
Definition at line 133 of file enc28j60.h.
Referenced by enc_set_bank().
#define BSEL1 0x02
Definition at line 132 of file enc28j60.h.
Referenced by enc_set_bank().
#define BUFER 0x40
Definition at line 95 of file enc28j60.h.
#define BUSY 0x01
Definition at line 453 of file enc28j60.h.
Referenced by enc_read_phy(), and enc_write_phy().
#define CLKRDY 0x01
Definition at line 100 of file enc28j60.h.
Referenced by enc_init().
#define COLSTAT 0x0800
Definition at line 313 of file enc28j60.h.
#define CRCEN 0x20
Definition at line 379 of file enc28j60.h.
Referenced by enc_init().
#define CSUMEN 0x10
Definition at line 129 of file enc28j60.h.
#define DMAIE 0x20
Definition at line 61 of file enc28j60.h.
#define DMAIF 0x20
Definition at line 78 of file enc28j60.h.
#define DMAST 0x20
Definition at line 128 of file enc28j60.h.
#define DPXSTAT 0x0200
Definition at line 315 of file enc28j60.h.
#define E_RXEN 0x04
Definition at line 131 of file enc28j60.h.
Referenced by enc_init().
#define EBSTCON (0x07 | BANK3)
Definition at line 231 of file enc28j60.h.
#define EBSTCSH (0x09 | BANK3)
Definition at line 233 of file enc28j60.h.
#define EBSTCSL (0x08 | BANK3)
Definition at line 232 of file enc28j60.h.
#define EBSTSD (0x06 | BANK3)
Definition at line 230 of file enc28j60.h.
#define ECOCON (0x15 | BANK3)
Definition at line 236 of file enc28j60.h.
#define ECON1 0x1F
Definition at line 124 of file enc28j60.h.
Referenced by enc_init(), enc_send_packet(), and enc_set_bank().
#define ECON2 0x1E
Definition at line 109 of file enc28j60.h.
Referenced by enc_recv_packet().
#define ECON2_R 0x10
Definition at line 114 of file enc28j60.h.
#define EDMACSH (0x17 | BANK0)
Definition at line 163 of file enc28j60.h.
#define EDMACSL (0x16 | BANK0)
Definition at line 162 of file enc28j60.h.
#define EDMADSTH (0x15 | BANK0)
Definition at line 161 of file enc28j60.h.
#define EDMADSTL (0x14 | BANK0)
Definition at line 160 of file enc28j60.h.
#define EDMANDH (0x13 | BANK0)
Definition at line 159 of file enc28j60.h.
#define EDMANDL (0x12 | BANK0)
Definition at line 158 of file enc28j60.h.
#define EDMASTH (0x11 | BANK0)
Definition at line 157 of file enc28j60.h.
#define EDMASTL (0x10 | BANK0)
Definition at line 156 of file enc28j60.h.
#define EFLOCON (0x17 | BANK3)
Definition at line 237 of file enc28j60.h.
#define EHT0 (0x00 | BANK1)
Definition at line 170 of file enc28j60.h.
#define EHT1 (0x01 | BANK1)
Definition at line 171 of file enc28j60.h.
#define EHT2 (0x02 | BANK1)
Definition at line 172 of file enc28j60.h.
#define EHT3 (0x03 | BANK1)
Definition at line 173 of file enc28j60.h.
#define EHT4 (0x04 | BANK1)
Definition at line 174 of file enc28j60.h.
#define EHT5 (0x05 | BANK1)
Definition at line 175 of file enc28j60.h.
#define EHT6 (0x06 | BANK1)
Definition at line 176 of file enc28j60.h.
#define EHT7 (0x07 | BANK1)
Definition at line 177 of file enc28j60.h.
#define EIE 0x1B
Definition at line 57 of file enc28j60.h.
Referenced by enc_init().
#define EIE_WOLIE 0x04
Definition at line 64 of file enc28j60.h.
#define EIR 0x1C
Definition at line 75 of file enc28j60.h.
#define EIR_WOLIF 0x04
Definition at line 81 of file enc28j60.h.
#define EPAUSH (0x19 | BANK3)
Definition at line 239 of file enc28j60.h.
#define EPAUSL (0x18 | BANK3)
Definition at line 238 of file enc28j60.h.
#define EPKTCNT (0x19 | BANK1)
Definition at line 193 of file enc28j60.h.
Referenced by enc_recv_packet().
#define EPMCSH (0x11 | BANK1)
Definition at line 187 of file enc28j60.h.
Referenced by enc_init().
#define EPMCSL (0x10 | BANK1)
Definition at line 186 of file enc28j60.h.
Referenced by enc_init().
#define EPMM0 (0x08 | BANK1)
Definition at line 178 of file enc28j60.h.
Referenced by enc_init().
#define EPMM1 (0x09 | BANK1)
Definition at line 179 of file enc28j60.h.
Referenced by enc_init().
#define EPMM2 (0x0A | BANK1)
Definition at line 180 of file enc28j60.h.
#define EPMM3 (0x0B | BANK1)
Definition at line 181 of file enc28j60.h.
#define EPMM4 (0x0C | BANK1)
Definition at line 182 of file enc28j60.h.
#define EPMM5 (0x0D | BANK1)
Definition at line 183 of file enc28j60.h.
#define EPMM6 (0x0E | BANK1)
Definition at line 184 of file enc28j60.h.
#define EPMM7 (0x0F | BANK1)
Definition at line 185 of file enc28j60.h.
#define EPMOH (0x15 | BANK1)
Definition at line 189 of file enc28j60.h.
#define EPMOL (0x14 | BANK1)
Definition at line 188 of file enc28j60.h.
#define ERDPTH (0x01 | BANK0)
Definition at line 141 of file enc28j60.h.
Referenced by enc_recv_packet().
#define ERDPTL (0x00 | BANK0)
Definition at line 140 of file enc28j60.h.
Referenced by enc_recv_packet().
#define EREVID (0x12 | BANK3)
Definition at line 235 of file enc28j60.h.
Referenced by enc_get_rev().
#define ERXFCON (0x18 | BANK1)
Definition at line 192 of file enc28j60.h.
Referenced by enc_init().
#define ERXNDH (0x0B | BANK0)
Definition at line 151 of file enc28j60.h.
Referenced by enc_init().
#define ERXNDL (0x0A | BANK0)
Definition at line 150 of file enc28j60.h.
Referenced by enc_init().
#define ERXRDPTH (0x0D | BANK0)
Definition at line 153 of file enc28j60.h.
Referenced by enc_init(), and enc_recv_packet().
#define ERXRDPTL (0x0C | BANK0)
Definition at line 152 of file enc28j60.h.
Referenced by enc_init(), and enc_recv_packet().
#define ERXSTH (0x09 | BANK0)
Definition at line 149 of file enc28j60.h.
Referenced by enc_init().
#define ERXSTL (0x08 | BANK0)
Definition at line 148 of file enc28j60.h.
Referenced by enc_init().
#define ERXWRPTH (0x0F | BANK0)
Definition at line 155 of file enc28j60.h.
#define ERXWRPTL (0x0E | BANK0)
Definition at line 154 of file enc28j60.h.
#define ESTAT 0x1D
Definition at line 92 of file enc28j60.h.
Referenced by enc_init().
#define ESTAT_R 0x20
Definition at line 96 of file enc28j60.h.
#define ETXNDH (0x07 | BANK0)
Definition at line 147 of file enc28j60.h.
Referenced by enc_init(), and enc_send_packet().
#define ETXNDL (0x06 | BANK0)
Definition at line 146 of file enc28j60.h.
Referenced by enc_init(), and enc_send_packet().
#define ETXSTH (0x05 | BANK0)
Definition at line 145 of file enc28j60.h.
Referenced by enc_init().
#define ETXSTL (0x04 | BANK0)
Definition at line 144 of file enc28j60.h.
Referenced by enc_init().
#define EWOLIE (0x16 | BANK1)
Definition at line 190 of file enc28j60.h.
#define EWOLIR (0x17 | BANK1)
Definition at line 191 of file enc28j60.h.
#define EWRPTH (0x03 | BANK0)
Definition at line 143 of file enc28j60.h.
Referenced by enc_send_packet().
#define EWRPTL (0x02 | BANK0)
Definition at line 142 of file enc28j60.h.
Referenced by enc_send_packet().
#define FRCLNK 0x4000
Definition at line 295 of file enc28j60.h.
#define FRMLNEN 0x02
Definition at line 429 of file enc28j60.h.
Referenced by enc_init().
#define FULDPX 0x01
Definition at line 430 of file enc28j60.h.
#define HDLDIS 0x0100
Definition at line 298 of file enc28j60.h.
Referenced by enc_init().
#define HFRMEN 0x04
Definition at line 428 of file enc28j60.h.
#define HTEN 0x04
Definition at line 382 of file enc28j60.h.
#define INT 0x80
Definition at line 94 of file enc28j60.h.
#define INTIE 0x80
Definition at line 59 of file enc28j60.h.
Referenced by enc_init().
#define JABBER 0x0400
Definition at line 297 of file enc28j60.h.
#define JBSTAT 0x0002
Definition at line 276 of file enc28j60.h.
#define LACFG0 0x0100
Definition at line 360 of file enc28j60.h.
#define LACFG1 0x0200
Definition at line 359 of file enc28j60.h.
#define LACFG2 0x0400
Definition at line 358 of file enc28j60.h.
#define LACFG3 0x0800
Definition at line 357 of file enc28j60.h.
#define LATECOL 0x10
Definition at line 97 of file enc28j60.h.
#define LBCFG0 0x0010
Definition at line 364 of file enc28j60.h.
#define LBCFG1 0x0020
Definition at line 363 of file enc28j60.h.
#define LBCFG2 0x0040
Definition at line 362 of file enc28j60.h.
#define LBCFG3 0x0080
Definition at line 361 of file enc28j60.h.
#define LFRQ0 0x0004
Definition at line 366 of file enc28j60.h.
#define LFRQ1 0x0008
Definition at line 365 of file enc28j60.h.
#define LINKIE 0x10
Definition at line 62 of file enc28j60.h.
#define LINKIF 0x10
Definition at line 79 of file enc28j60.h.
#define LLSTAT 0x0004
Definition at line 275 of file enc28j60.h.
#define LOOPBK 0x10
Definition at line 394 of file enc28j60.h.
#define LSTAT 0x0400
Definition at line 314 of file enc28j60.h.
#define MAADR0 (0x01 | BANK3 | 0x80)
Definition at line 225 of file enc28j60.h.
Referenced by enc_set_mac().
#define MAADR1 (0x00 | BANK3 | 0x80)
Definition at line 224 of file enc28j60.h.
Referenced by enc_set_mac().
#define MAADR2 (0x03 | BANK3 | 0x80)
Definition at line 227 of file enc28j60.h.
Referenced by enc_set_mac().
#define MAADR3 (0x02 | BANK3 | 0x80)
Definition at line 226 of file enc28j60.h.
Referenced by enc_set_mac().
#define MAADR4 (0x05 | BANK3 | 0x80)
Definition at line 229 of file enc28j60.h.
Referenced by enc_set_mac().
#define MAADR5 (0x04 | BANK3 | 0x80)
Definition at line 228 of file enc28j60.h.
Referenced by enc_set_mac().
#define MABBIPG (0x04 | BANK2 | 0x80)
Definition at line 204 of file enc28j60.h.
Referenced by enc_init().
#define MACLCON1 (0x08 | BANK2 | 0x80)
Definition at line 207 of file enc28j60.h.
#define MACLCON2 (0x09 | BANK2 | 0x80)
Definition at line 208 of file enc28j60.h.
#define MACON1 (0x00 | BANK2 | 0x80)
Definition at line 200 of file enc28j60.h.
Referenced by enc_init().
#define MACON2 (0x01 | BANK2 | 0x80)
Definition at line 201 of file enc28j60.h.
Referenced by enc_init().
#define MACON3 (0x02 | BANK2 | 0x80)
Definition at line 202 of file enc28j60.h.
Referenced by enc_init().
#define MACON4 (0x03 | BANK2 | 0x80)
Definition at line 203 of file enc28j60.h.
#define MAIPGH (0x07 | BANK2 | 0x80)
Definition at line 206 of file enc28j60.h.
Referenced by enc_init().
#define MAIPGL (0x06 | BANK2 | 0x80)
Definition at line 205 of file enc28j60.h.
Referenced by enc_init().
#define MAMXFLH (0x0B | BANK2 | 0x80)
Definition at line 210 of file enc28j60.h.
Referenced by enc_init().
#define MAMXFLL (0x0A | BANK2 | 0x80)
Definition at line 209 of file enc28j60.h.
Referenced by enc_init().
#define MAPHSUP (0x0D | BANK2 | 0x80)
Definition at line 211 of file enc28j60.h.
#define MARST 0x80
Definition at line 408 of file enc28j60.h.
#define MARXEN 0x01
Definition at line 398 of file enc28j60.h.
Referenced by enc_init().
#define MARXRST 0x08
Definition at line 410 of file enc28j60.h.
#define MATXRST 0x02
Definition at line 412 of file enc28j60.h.
#define MAX_FRAME_LEN 1500
Definition at line 483 of file enc28j60.h.
Referenced by enc_init().
#define MCEN 0x02
Definition at line 383 of file enc28j60.h.
#define MICMD (0x12 | BANK2 | 0x80)
Definition at line 213 of file enc28j60.h.
Referenced by enc_read_phy().
#define MICON (0x11 | BANK2 | 0x80)
Definition at line 212 of file enc28j60.h.
#define MIIRD 0x01
Definition at line 441 of file enc28j60.h.
Referenced by enc_read_phy().
#define MIISCAN 0x02
Definition at line 440 of file enc28j60.h.
#define MIRDH (0x19 | BANK2 | 0x80)
Definition at line 218 of file enc28j60.h.
Referenced by enc_read_phy().
#define MIRDL (0x18 | BANK2 | 0x80)
Definition at line 217 of file enc28j60.h.
Referenced by enc_read_phy().
#define MIREGADR (0x14 | BANK2 | 0x80)
Definition at line 214 of file enc28j60.h.
Referenced by enc_read_phy(), and enc_write_phy().
#define MISTAT (0x0A | BANK3 | 0x80)
Definition at line 234 of file enc28j60.h.
Referenced by enc_read_phy(), and enc_write_phy().
#define MIWRH (0x17 | BANK2 | 0x80)
Definition at line 216 of file enc28j60.h.
Referenced by enc_write_phy().
#define MIWRL (0x16 | BANK2 | 0x80)
Definition at line 215 of file enc28j60.h.
Referenced by enc_write_phy().
#define MPEN 0x08
Definition at line 381 of file enc28j60.h.
#define NVALID 0x04
Definition at line 451 of file enc28j60.h.
#define PADCFG0 0x20
Definition at line 425 of file enc28j60.h.
Referenced by enc_init().
#define PADCFG1 0x40
Definition at line 424 of file enc28j60.h.
#define PADCFG2 0x80
Definition at line 423 of file enc28j60.h.
#define PASSALL 0x02
Definition at line 397 of file enc28j60.h.
#define PCRCEN 0x02
Definition at line 464 of file enc28j60.h.
#define PDPXMD 0x0100
Definition at line 260 of file enc28j60.h.
#define PFDPX 0x1000
Definition at line 273 of file enc28j60.h.
#define PGEIE 0x0002
Definition at line 330 of file enc28j60.h.
#define PGIF 0x0004
Definition at line 344 of file enc28j60.h.
#define PHCON1 0x00
Definition at line 255 of file enc28j60.h.
#define PHCON2 0x10
Definition at line 293 of file enc28j60.h.
Referenced by enc_init().
#define PHDPX 0x0800
Definition at line 274 of file enc28j60.h.
#define PHDREN 0x08
Definition at line 427 of file enc28j60.h.
#define PHHID1 0x02
Definition at line 279 of file enc28j60.h.
#define PHHID2 0x03
Definition at line 282 of file enc28j60.h.
#define PHIE 0x12
Definition at line 327 of file enc28j60.h.
#define PHIR 0x13
Definition at line 341 of file enc28j60.h.
#define PHLCON 0x14
Definition at line 355 of file enc28j60.h.
Referenced by enc_init_phy().
#define PHSTAT1 0x01
Definition at line 271 of file enc28j60.h.
#define PHSTAT2 0x11
Definition at line 309 of file enc28j60.h.
#define PHUGEEN 0x08
Definition at line 462 of file enc28j60.h.
#define PKTDEC 0x40
Definition at line 112 of file enc28j60.h.
Referenced by enc_recv_packet().
#define PKTIE 0x40
Definition at line 60 of file enc28j60.h.
Referenced by enc_init().
#define PKTIF 0x40
Definition at line 77 of file enc28j60.h.
#define PLNKIE 0x0010
Definition at line 329 of file enc28j60.h.
#define PLNKIF 0x0010
Definition at line 343 of file enc28j60.h.
#define PLOOPBK 0x4000
Definition at line 258 of file enc28j60.h.
#define PLRITY 0x0020
Definition at line 316 of file enc28j60.h.
#define PMEN 0x10
Definition at line 380 of file enc28j60.h.
Referenced by enc_init().
#define POVERRIDE 0x01
Definition at line 465 of file enc28j60.h.
#define PPADEN 0x04
Definition at line 463 of file enc28j60.h.
#define PPWRSV 0x0800
Definition at line 259 of file enc28j60.h.
#define PRST 0x8000
Definition at line 257 of file enc28j60.h.
#define PWRSV 0x20
Definition at line 113 of file enc28j60.h.
#define READ_BUF_MEM 0x3A
Definition at line 471 of file enc28j60.h.
Referenced by enc_read_buf(), and enc_recv_packet().
#define READ_CTRL_REG 0x00
Definition at line 470 of file enc28j60.h.
Referenced by enc_read().
#define RFUNRST 0x04
Definition at line 411 of file enc28j60.h.
#define RNDRST 0x40
Definition at line 409 of file enc28j60.h.
#define RX_START_INIT 0x00
Definition at line 478 of file enc28j60.h.
Referenced by enc_init().
#define RX_STOP_INIT (0x1FFF - 0x0600 - 1)
Definition at line 479 of file enc28j60.h.
Referenced by enc_init().
#define RXBUSY 0x04
Definition at line 98 of file enc28j60.h.
#define RXERIE 0x01
Definition at line 66 of file enc28j60.h.
#define RXERIF 0x01
Definition at line 83 of file enc28j60.h.
#define RXPAUS 0x04
Definition at line 396 of file enc28j60.h.
Referenced by enc_init().
#define RXRST 0x40
Definition at line 127 of file enc28j60.h.
#define RXSTAT 0x1000
Definition at line 312 of file enc28j60.h.
#define SCAN 0x02
Definition at line 452 of file enc28j60.h.
#define SOFT_RESET 0xFF
Definition at line 476 of file enc28j60.h.
Referenced by enc_init().
#define SPRD_MASK 0x80
Definition at line 48 of file enc28j60.h.
#define STRCH 0x0002
Definition at line 367 of file enc28j60.h.
#define TFUNRST 0x01
Definition at line 413 of file enc28j60.h.
#define TX_START_INIT (0x1FFF - 0x0600)
Definition at line 480 of file enc28j60.h.
Referenced by enc_init(), and enc_send_packet().
#define TX_STOP_INIT 0x1FFF
Definition at line 481 of file enc28j60.h.
Referenced by enc_init().
#define TXABRT 0x02
Definition at line 99 of file enc28j60.h.
#define TXCRCEN 0x10
Definition at line 426 of file enc28j60.h.
Referenced by enc_init().
#define TXDIS 0x2000
Definition at line 296 of file enc28j60.h.
#define TXERIE 0x02
Definition at line 65 of file enc28j60.h.
#define TXERIF 0x02
Definition at line 82 of file enc28j60.h.
#define TXIE 0x08
Definition at line 63 of file enc28j60.h.
#define TXIF 0x08
Definition at line 80 of file enc28j60.h.
#define TXPAUS 0x08
Definition at line 395 of file enc28j60.h.
Referenced by enc_init().
#define TXRST 0x80
Definition at line 126 of file enc28j60.h.
#define TXRTS 0x08
Definition at line 130 of file enc28j60.h.
Referenced by enc_send_packet().
#define TXSTAT 0x2000
Definition at line 311 of file enc28j60.h.
#define UCEN 0x80
Definition at line 377 of file enc28j60.h.
Referenced by enc_init().
#define VRPF 0x08
Definition at line 115 of file enc28j60.h.
#define WRITE_BUF_MEM 0x7A
Definition at line 473 of file enc28j60.h.
Referenced by enc_send_packet(), and enc_write_buf().
#define WRITE_CTRL_REG 0x40
Definition at line 472 of file enc28j60.h.
Referenced by enc_write().
Function Documentation
uint8_t enc_get_rev (void)
get the revision of ENC28J60
Returns
revision
Definition at line 332 of file enc28j60.c.
References enc_read(), and EREVID.
void enc_init (uint8_t *)
Referenced by main().
void enc_init_phy (void)
initialize the physical interface of ENC28J60
Definition at line 270 of file enc28j60.c.
References enc_write_phy(), and PHLCON.
Referenced by main().
uint8_t enc_read (uint8_t addr)
read from from address of ENC28J60
Parameters
addr address
Returns
operation
Definition at line 235 of file enc28j60.c.
References enc_read_op(), enc_set_bank(), and READ_CTRL_REG.
Referenced by enc_get_rev(), enc_init(), enc_read_phy(), enc_recv_packet(), and enc_write_phy().
void enc_read_buf (uint16_t len, uint8_t * data)
read from the buffer
Parameters
len length of data
data data to read
Definition at line 295 of file enc28j60.c.
References enc_start(), enc_stop(), READ_BUF_MEM, spi_read(), and spi_write().
Referenced by enc_recv_packet().
uint8_t enc_read_op (uint8_t op, uint8_t addr)
read the operation from address of ENC28J60
Parameters
op operation
addr address
Returns
data from SPI
Definition at line 251 of file enc28j60.c.
References enc_start(), enc_stop(), spi_read_addr(), spi_write(), and spi_write_op().
Referenced by enc_read(), and enc_recv_packet().
uint16_t enc_read_phy (uint8_t addr)
read from physical address of ENC28J60
Parameters
addr address
Returns
data
Definition at line 209 of file enc28j60.c.
References BUSY, enc_read(), enc_write(), MICMD, MIIRD, MIRDH, MIRDL, MIREGADR, and MISTAT.
uint16_t enc_recv_packet (uint16_t maxlen, uint8_t * packet)
receive a packet from ethernet
Parameters
maxlen maximum length of packet to receive
packet packet to receive
Returns
length of received packet
Definition at line 368 of file enc28j60.c.
References BIT_FIELD_SET, ECON2, enc_read(), enc_read_buf(), enc_read_op(), enc_write(), enc_write_op(), EPKTCNT, ERDPTH, ERDPTL, ERXRDPTH, ERXRDPTL, MIN, p_next, PKTDEC, and READ_BUF_MEM.
Referenced by main().
void enc_send_packet (uint16_t len, uint8_t * packet)
send a packet to ethernet
Parameters
len length of packet
packet packet to send
Definition at line 344 of file enc28j60.c.
References BIT_FIELD_SET, ECON1, enc_write(), enc_write_buf(), enc_write_op(), ETXNDH, ETXNDL, EWRPTH, EWRPTL, TX_START_INIT, TXRTS, and WRITE_BUF_MEM.
Referenced by arp_answer(), echo_reply(), and udp_reply().
void enc_set_bank (uint8_t addr)
set the bank on address
Parameters
addr address to set
Definition at line 174 of file enc28j60.c.
References ADDR_MASK, BANK_MASK, BIT_FIELD_CLR, BIT_FIELD_SET, BSEL0, BSEL1, ECON1, enc_bank, and enc_write_op().
Referenced by enc_init(), enc_read(), and enc_write().
void enc_set_mac (uint8_t *)
void enc_start (void)
start ENC28J60 pin to write or to read
Definition at line 38 of file enc28j60.c.
References ENC_CTRL_CS, and ENC_CTRL_PORT.
Referenced by enc_read_buf(), enc_read_op(), enc_write_buf(), and enc_write_op().
void enc_stop (void)
stop the ENC28J60 pin
Definition at line 47 of file enc28j60.c.
References ENC_CTRL_CS, and ENC_CTRL_PORT.
Referenced by enc_read_buf(), enc_read_op(), enc_write_buf(), and enc_write_op().
void enc_write (uint8_t addr, uint8_t data)
write on ENC28J60
Parameters
addr address to write
data data to send
Definition at line 162 of file enc28j60.c.
References enc_set_bank(), enc_write_op(), and WRITE_CTRL_REG.
Referenced by enc_init(), enc_read_phy(), enc_recv_packet(), enc_send_packet(), enc_set_mac(), and enc_write_phy().
void enc_write_buf (uint16_t len, uint8_t * data)
write the buffer
Parameters
len length of data
data data
Definition at line 314 of file enc28j60.c.
References enc_start(), enc_stop(), spi_write(), and WRITE_BUF_MEM.
Referenced by enc_send_packet().
void enc_write_op (uint8_t op, uint8_t addr, uint8_t data)
write the operation
Parameters
op operation to write on SPI
addr address to write
data data to send on SPI
Definition at line 145 of file enc28j60.c.
References enc_start(), enc_stop(), spi_write(), and spi_write_op().
Referenced by enc_init(), enc_recv_packet(), enc_send_packet(), enc_set_bank(), and enc_write().
void enc_write_phy (uint8_t addr, uint16_t data)
write the data on ENC28J60 physical address
Parameters
addr address
data data
Definition at line 190 of file enc28j60.c.
References BUSY, enc_read(), enc_write(), MIREGADR, MISTAT, MIWRH, and MIWRL.
Referenced by enc_init(), and enc_init_phy().