driver/icp.h File Reference
header file for input capture pin operations
#include <device/atmega16.h>
*
Functions
void icp_init (void(*)(uint16_t))
initialize the input capture pin on timer 1
Variables
void(* icp_handler)(uint16_t)
Detailed Description
header file for input capture pin operations
Author
M. Ozgan, mozgan@mozgan.org
Version
0.1
Date
22.08.2013 15:56:37
Compiler
gcc (on Mac, and 4.4BSD)
Company
TU Wien
Bug
Bug none
Todo
Todo none
Definition in file icp.h.
Function Documentation
void icp_init (void(*)(uint16_t) call_back)
initialize the input capture pin on timer 1
Parameters
call_back call back function from interrupt to call
Definition at line 36 of file icp.c.
References F_CPU, icp_handler, and NULL.
Referenced by main().
Variable Documentation
void(* icp_handler)(uint16_t)
call back function
Definition at line 34 of file icp.h.
Referenced by icp_init(), and ISR().