main.c File Reference
main program
#include <stdio.h>
*
#include <stdlib.h>
*
#include <string.h>
*
#include <avr/io.h>
*
#include <util/delay.h>
*
#include <include/common.h>
*
#include <board/freq.h>
*
#include <lib/buffer.h>
*
#include <driver/leds.h>
*
#include <device/enc28j60.h>
*
#include <driver/net.h>
*
#include <driver/icp.h>
*
Macros
#define BUF_SIZE 150
Functions
void trigger (uint16_t icr)
return-function from input capture interrupt routine
int main (void)
main function (program start)
Variables
static uint8_t buf [BUF_SIZE]
uint8_t mymac [6] = {0xab,0xbc,0x6f,0x55,0x1c,0xc2}
uint8_t myip [4] = {192, 168, 0, 3}
uint16_t myport = 1200
volatile uint16_t plen
volatile uint16_t new
volatile uint16_t old
volatile uint16_t diff
volatile float freq
volatile int snd = 0
Detailed Description
main program
Author
M. Ozgan, mozgan@mozgan.org
Version
0.5
Date
19.08.2013 15:20:15
Compiler
gcc (on Mac, and 4.4BSD)
Company
TU Wien
Bug
Bug
signal has not readed!
Todo
Todo none
Definition in file main.c.
Macro Definition Documentation
#define BUF_SIZE 150
Definition at line 43 of file main.c.
Referenced by main().
Function Documentation
int main (void)
main function (program start)
Returns
returns zero if SUCCESS, otherwise non-zero
Definition at line 89 of file main.c.
References arp_answer(), buf, BUF_SIZE, buffer_init(), buffer_medium(), diff, echo_reply(), enc_init(), enc_init_phy(), enc_recv_packet(), eth_arp(), eth_ip(), F_CPU, freq, ICMP_REQUEST_V, ICMP_TYPE_P, icp_init(), IP_PROTO_ICMP_V, IP_PROTO_P, IP_PROTO_UDP_V, leds_init(), LEN, myip, mymac, myport, net_init(), plen, snd, trigger(), TRUE, and udp_reply().
void trigger (uint16_t icr)
return-function from input capture interrupt routine
Parameters
icr input capture timer state
Definition at line 65 of file main.c.
References buffer_write(), led_toggle(), LEN, old, and snd.
Referenced by main().
Variable Documentation
uint8_t buf[BUF_SIZE] [static]
Definition at line 45 of file main.c.
Referenced by checksum(), and main().
volatile uint16_t diff
Definition at line 54 of file main.c.
Referenced by main().
volatile float freq
Definition at line 55 of file main.c.
Referenced by main().
uint8_t myip[4] = {192, 168, 0, 3}
Definition at line 48 of file main.c.
Referenced by main().
uint8_t mymac[6] = {0xab,0xbc,0x6f,0x55,0x1c,0xc2}
Definition at line 47 of file main.c.
Referenced by main().
uint16_t myport = 1200
Definition at line 49 of file main.c.
Referenced by main().
volatile uint16_t new
Definition at line 53 of file main.c.
volatile uint16_t old
Definition at line 53 of file main.c.
Referenced by trigger().
volatile uint16_t plen
Definition at line 51 of file main.c.
Referenced by main().
volatile int snd = 0
Definition at line 57 of file main.c.
Referenced by main(), and trigger().