driver/net.c File Reference
driver for network communication
#include <board/freq.h>
*
#include <device/enc28j60.h>
*
#include <driver/net.h>
*
#include <driver/leds.h>
*
Functions
void net_init (uint8_t *mymac, uint8_t *myip)
initialize the network
uint8_t eth_arp (uint8_t *buf, uint8_t len)
make the network wirh arp
uint8_t eth_ip (uint8_t *buf, uint8_t len)
make the network communication with ip address
void arp_answer (uint8_t *buf, uint8_t len)
make an answer if request
void echo_reply (uint8_t *buf, uint8_t len)
make an echo answer (ping - pong) if request
void udp_reply (uint8_t *buf, char *data, uint8_t len, uint16_t port)
make the UDP protocol
void make_eth (uint8_t *buf)
make the ethernet header
void make_ip (uint8_t *buf)
make the ip header
uint16_t checksum (uint8_t *buf, uint16_t len, uint8_t type)
checksum
Variables
static uint8_t macaddr [6]
static uint8_t ipaddr [4]
Detailed Description
driver for network communication
Author
M. Ozgan, mozgan@mozgan.org
Version
0.2
Date
20.08.2013 13:29:36
Compiler
gcc (on Mac, GNU/Linux, 4.4BSD)
Company
TU Wien
Bug
Bug none
Todo
Todo none
Definition in file net.c.
Function Documentation
void arp_answer (uint8_t * buf, uint8_t len)
make an answer if request
Parameters
buf buffer
len length of buffer
Definition at line 125 of file net.c.
References ARP_DEST_IP_P, ARP_DEST_MAC_P, ARP_OPCODE_H_P, ARP_OPCODE_L_P, ARP_OPCODE_REPLY_H_V, ARP_OPCODE_REPLY_L_V, ARP_SRC_IP_P, ARP_SRC_MAC_P, enc_send_packet(), ipaddr, macaddr, and make_eth().
Referenced by main().
uint16_t checksum (uint8_t * buf, uint16_t len, uint8_t type)
checksum
Parameters
buf buffer
len length
type type
Returns
sum
Definition at line 277 of file net.c.
References buf, IP_PROTO_TCP_V, and IP_PROTO_UDP_V.
Referenced by make_ip(), and udp_reply().
void echo_reply (uint8_t * buf, uint8_t len)
make an echo answer (ping - pong) if request
Parameters
buf buffer
len length of buffer
Definition at line 158 of file net.c.
References enc_send_packet(), ICMP_CHECKSUM_P, ICMP_REPLY_V, ICMP_TYPE_P, make_eth(), and make_ip().
Referenced by main().
uint8_t eth_arp (uint8_t * buf, uint8_t len)
make the network wirh arp
Parameters
buf buffer
len length of buffer
Returns
return 1 if success, otherwise zero
Definition at line 67 of file net.c.
References ARP_DEST_IP_P, ETH_TYPE_H_P, ETH_TYPE_L_P, ETHTYPE_ARP_H_V, ETHTYPE_ARP_L_V, and ipaddr.
Referenced by main().
uint8_t eth_ip (uint8_t * buf, uint8_t len)
make the network communication with ip address
Parameters
buf buffer
len length of buffer
Returns
returns 1 if success, otherwise zero
Definition at line 97 of file net.c.
References ETH_TYPE_H_P, ETH_TYPE_L_P, ETHTYPE_IP_H_V, ETHTYPE_IP_L_V, IP_DEST_P, and ipaddr.
Referenced by main().
void make_eth (uint8_t * buf)
make the ethernet header
Parameters
buf buffer
Definition at line 225 of file net.c.
References ETH_DEST_MAC, ETH_SRC_MAC, and macaddr.
Referenced by arp_answer(), echo_reply(), and udp_reply().
void make_ip (uint8_t * buf)
make the ip header
Parameters
buf
Definition at line 242 of file net.c.
References checksum(), IP_CHECKSUM_P, IP_DEST_P, IP_FLAGS_P, IP_HEADER_LEN, IP_P, IP_SRC_P, IP_TTL_P, and ipaddr.
Referenced by echo_reply(), and udp_reply().
void net_init (uint8_t * mymac, uint8_t * myip)
initialize the network
Parameters
mymac my mac address
myip my ip address
Definition at line 43 of file net.c.
References ipaddr, and macaddr.
Referenced by main().
void udp_reply (uint8_t * buf, char * data, uint8_t len, uint16_t port)
make the UDP protocol
Parameters
buf buffer
data data
len length
port port number
Definition at line 182 of file net.c.
References checksum(), enc_send_packet(), ETH_HEADER_LEN, IP_HEADER_LEN, IP_SRC_P, IP_TOTLEN_H_P, IP_TOTLEN_L_P, make_eth(), make_ip(), UDP_CHECKSUM_H_P, UDP_CHECKSUM_L_P, UDP_DATA_P, UDP_DEST_PORT_H_P, UDP_DEST_PORT_L_P, UDP_HEADER_LEN, UDP_LEN_H_P, UDP_LEN_L_P, UDP_SRC_PORT_H_P, and UDP_SRC_PORT_L_P.
Referenced by main().
Variable Documentation
uint8_t ipaddr[4] [static]
Definition at line 34 of file net.c.
Referenced by arp_answer(), eth_arp(), eth_ip(), make_ip(), and net_init().
uint8_t macaddr[6] [static]
Definition at line 33 of file net.c.
Referenced by arp_answer(), make_eth(), and net_init().