driver/spi.c File Reference
driver for spi interface
#include <driver/spi.h>
*
Functions
void spi_init (void)
initialize SPI communication
void spi_write_op (uint8_t op, uint8_t addr)
write an operation to address
void spi_write (uint8_t data)
write the data to SPI
uint8_t spi_read_addr (uint8_t addr)
read from address
uint8_t spi_read (void)
read from SPI data register
Detailed Description
driver for spi interface
Author
M. Ozgan, mozgan@mozgan.org
Version
0.1
Date
20.08.2013 14:52:49
Compiler
gcc (on Mac, and 4.4BSD)
Company
TU Wien
Bug
Bug none
Todo
Todo none
Definition in file spi.c.
Function Documentation
void spi_init (void)
initialize SPI communication
Definition at line 33 of file spi.c.
References SPI_CONTROL_REG, SPI_DDR, SPI_DOUBLE_SPEED, SPI_ENABLE, SPI_MASTER, SPI_MISO, SPI_MOSI, SPI_PORT, SPI_SCK, SPI_SS, and SPI_STATUS_REG.
Referenced by enc_init().
uint8_t spi_read (void)
read from SPI data register
Returns
value of SPI data register
Definition at line 102 of file spi.c.
Referenced by enc_read_buf().
uint8_t spi_read_addr (uint8_t addr)
read from address
Parameters
addr address
Returns
Definition at line 84 of file spi.c.
Referenced by enc_read_op().
void spi_write (uint8_t data)
write the data to SPI
Parameters
data data
Definition at line 68 of file spi.c.
References SPI_INT_FLAG, and SPI_STATUS_REG.
Referenced by enc_read_buf(), enc_read_op(), enc_write_buf(), and enc_write_op().
void spi_write_op (uint8_t op, uint8_t addr)
write an operation to address
Parameters
op operation
addr address
Definition at line 54 of file spi.c.
References ADDR_MASK, SPI_DATA_REG, SPI_INT_FLAG, and SPI_STATUS_REG.
Referenced by enc_read_op(), and enc_write_op().